travis:
  secure:
    BINSTAR_TOKEN: aU7AMf8ifuBTekTlR5fjaF3K8ImD0Vf1rT2QYYvOb3mYkPUwOmutpBVZ0zk3JjnPyysnBVx7unlZ+ZV0lRvZd4CZ/apzbgWwec3eZeSRjWzX9xPGpkwPI3EX19U+WeP8Fy+poJmF9sHrpcWp0KSQwg22P1XoR7rmJjSp2QZhElTmXslz1ey4bY6MdqMgmaILAIyPT8vmiWpIvm6Bf0ON4zbKb1ocwsLZmM77CCqgxvbeFtICeh3W7y4XuK/d5PtO71nB6Zbb1xqWHhivhOq2Epa5XrDvErKrOhNhUoiSPZSB/xU/TeC+9lsGCXTATYw6ei+WwKMwYmhOp3mxlu6gv4IsBtZS/Z+rut8fPmQgYXdcW6Y6In1+6SuFhOGm3LWTuxwlhLpcMcoIbSwPQBAINl7F3+Su+4N4nCYI5hj4gaYcCFAjrfNpJbkZwdAbuNwsLqN98PsicYyeNgE4splbuOAPruoBNhobMv7/cVQ4w+gRNdxWzBXIJEU6ZiPkYbu5o4KypDU6rRmRGwNLGWZQrR/OXEMAQ56O6Czsm6wSLEEOU3MmciYNCjmV7iH4dezgx65tnHRViDpf6pAMjATjCPqfm5yYMEGfk9ULiIbhPl/O6ojESdTyQ6jfj8SZz6qyT8lpax7JX4eRLKNodDAO1NNVTg0TehgEt/CPg+SOwZs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
